
MusicDirector.create!(name: "Nathan Watts", email: "example_one@mail.com", password: "passw0rd...")
MusicDirector.create!(name: "Joe Guercio", email: "example_two@mail.com", password: "p@sswerd1")
MusicDirector.create!(name: "Brad Buxer", email: "example_three@mail.com", password: "¡pa55word!")
MusicDirector.create!(name: "Morris Hayes", email: "example_four@mail.com", password: "p@ss_w0rd")
MusicDirector.create!(name: "Yannick Nézet-Séguin", email: "example_five@mail.com", password: "Pass--W0rd")
MusicDirector.create!(name: "Kerry Marx", email: "example_nineteen@mail.com", password: "P@sswurd")


Instrument.create!(name: "Acoustic Guitar")
Instrument.create!(name: "Electric Guitar")
Instrument.create!(name: "Electric Bass")
Instrument.create!(name: "Piano")
Instrument.create!(name: "Drums")
Instrument.create!(name: "Keyboards")
Instrument.create!(name: "Vocals")
Instrument.create!(name: "Alto Sax")
Instrument.create!(name: "Tenor Sax")
Instrument.create!(name: "Trumpet")
Instrument.create!(name: "Violin")
Instrument.create!(name: "Cello")
Instrument.create!(name: "Upright Bass")


Genre.create!(name: "Rock")
Genre.create!(name: "Pop")
Genre.create!(name: "Jazz")
Genre.create!(name: "R&B")
Genre.create!(name: "Classical")
Genre.create!(name: "Hip-Hop/Rap")
Genre.create!(name: "Folk")
Genre.create!(name: "Country")
Genre.create!(name: "Broadway")
Genre.create!(name: "Blues")
Genre.create!(name: "Jazz")


Musician.create!(name: "Jimi Hendrix", email: "example_six@mail.com", password: "p@ss...word", instrument_id: 2, pay_rate: 250.25)
Musician.create!(name: "Freddie Mercury", email: "example_seven@mail.com", password: "!-0πåßß∑ø®", instrument_id: 7, pay_rate: 250.25)
Musician.create!(name: "Charlie Parker", email: "example_eight@mail.com", password: "-pa##w6rd-", instrument_id: 8, pay_rate: 250.25)
Musician.create!(name: "John Coltrane", email: "example_nine@mail.com", password: "p@st_word5", instrument_id: 9, pay_rate: 250.25)
Musician.create!(name: "Miles Davis", email: "example_ten@mail.com", password: "dr0wss@p", instrument_id: 10, pay_rate: 250.25)
Musician.create!(name: "Keith Moon", email: "example_eleven@mail.com", password: "dr@wss0p", instrument_id: 5, pay_rate: 250.25)
Musician.create!(name: "Stanley Clarke", email: "example_twelve@mail.com", password: "dp@5r05w", instrument_id: 3, pay_rate: 250.25)
Musician.create!(name: "Chick Corea", email: "example_thirteen@mail.com", password: "@w5P0dR5", instrument_id: 4, pay_rate: 250.25)
Musician.create!(name: "Hans Zimmer", email: "example_fourteen@mail.com", password: "P&ss558rd", instrument_id: 6, pay_rate: 250.25)
Musician.create!(name: "Charles Mingus", email: "example_fifteen@mail.com", password: "P@55inw0rds", instrument_id: 13, pay_rate: 250.25)
Musician.create!(name: "Yo Yo Ma", email: "example_sixteen@mail.com", password: "W0RdsTh@tP@ss", instrument_id: 12, pay_rate: 250.25)
Musician.create!(name: "Niccolo Paganinni", email: "example_seventeen@mail.com", password: "wurdswurdsW@RD5", instrument_id: 11, pay_rate: 250.25)
Musician.create!(name: "Django Reinhart", email: "example_eighteen@mail.com", password: "W@RD5W@RD5W@RD5", instrument_id: 1, pay_rate: 250.25)
Musician.create!(name: "Chet Atkins", email: "example_twenty@mail.com", password: "p@ss...word", instrument_id: 2, pay_rate: 250.25)
Musician.create!(name: "Merry Clayton", email: "example_twenty_one@mail.com", password: "!-0πåßß∑ø®", instrument_id: 7, pay_rate: 250.25)
Musician.create!(name: "Maceo Parker", email: "example_twenty_two@mail.com", password: "-pa##w6rd-", instrument_id: 8, pay_rate: 250.25)
Musician.create!(name: "David Sanborn", email: "example_twenty_three@mail.com", password: "p@st_word5", instrument_id: 9, pay_rate: 250.25)
Musician.create!(name: "Louis Armstrong", email: "example_twenty_four@mail.com", password: "dr0wss@p", instrument_id: 10, pay_rate: 250.25)
Musician.create!(name: "Clyde Stubblefield", email: "example_twenty_five@mail.com", password: "dr@wss0p", instrument_id: 5, pay_rate: 250.25)
Musician.create!(name: "Bootsy Collins", email: "example_twenty_six@mail.com", password: "dp@5r05w", instrument_id: 3, pay_rate: 250.25)
Musician.create!(name: "Rick Wakeman", email: "example_twenty_seven@mail.com", password: "@w5P0dR5", instrument_id: 4, pay_rate: 250.25)
Musician.create!(name: "Al Kooper", email: "example_twenty_eight@mail.com", password: "P&ss558rd", instrument_id: 6, pay_rate: 250.25)
Musician.create!(name: "Bob Moore", email: "example_twenty_nine@mail.com", password: "P@55inw0rds", instrument_id: 13, pay_rate: 250.25)
Musician.create!(name: "Jacqueline du Pre", email: "example_thirty@mail.com", password: "W0RdsTh@tP@ss", instrument_id: 12, pay_rate: 250.25)
Musician.create!(name: "Itzhak Perlman", email: "example_thirty_one@mail.com", password: "wurdswurdsW@RD5", instrument_id: 11, pay_rate: 250.25)
Musician.create!(name: "Tommy Emmannuel", email: "example_thirty_two@mail.com", password: "W@RD5W@RD5W@RD5", instrument_id: 1, pay_rate: 250.25)


Gig.create!(music_director_id: 1, genre_id: 3, title: "Jazz Combo @ The Village Vanguard", location: "The Village Underground – New York, NY", start_date: DateTime.new(2022,9,4,17,0,0), end_date: DateTime.new(2022,9,4,18,0,0), budget: 5000.00, instrument_ids: [3,4,8,9,10,13])
Gig.create!(music_director_id: 2, genre_id: 4, title: "Beethoven's 5th Symphony @ The Met", location: "The Metropolitan Opera House – New York, NY", start_date: DateTime.new(2022,9,15,19,0,0), end_date: DateTime.new(2022,9,15,20,0,0), budget: 5000.00)
Gig.create!(music_director_id: 3, genre_id: 1, title: "Funky Rock Show @ Rockwood", location: "Rockwood Music Hall– New York, NY", start_date: DateTime.new(2022,9,17,19,0,0), end_date: DateTime.new(2022,9,17,20,0,0), budget: 5000.00, instrument_ids: [2,3,5])
Gig.create!(music_director_id: 4, genre_id: 2, title: "The All-Star Band @ MSG", location: "Madison Square Garden – New York, NY", start_date: DateTime.new(2022,10,31,19,0,0), end_date: DateTime.new(2022,10,31,22,0,0), budget: 5000.00, instrument_ids: [2,3,4,5,6,7])
Gig.create!(music_director_id: 5, genre_id: 5, title: "The Big U.S. Tour", start_date: DateTime.new(2020,10,31), end_date: DateTime.new(2021,10,31))

Gig.first.book_musician(Musician.find_by(name: "Miles Davis"))
Gig.first.book_musician(Musician.find_by(name: "John Coltrane"))
Gig.first.book_musician(Musician.find_by(name: "Charlie Parker"))
Gig.first.book_musician(Musician.find_by(name: "Charles Mingus"))
Gig.first.book_musician(Musician.find_by(name: "Chick Corea"))
Gig.third.book_musician(Musician.find_by(name: "Jimi Hendrix"))
Gig.third.book_musician(Musician.find_by(name: "Clyde Stubblefield"))
Gig.third.book_musician(Musician.find_by(name: "Bootsy Collins"))
Gig.fourth.book_musician(Musician.find_by(name: "Merry Clayton"))
Gig.fourth.book_musician(Musician.find_by(name: "Bootsy Collins"))
Gig.fourth.book_musician(Musician.find_by(name: "Rick Wakeman"))
Gig.fourth.book_musician(Musician.find_by(name: "Chet Atkins"))
Gig.fourth.book_musician(Musician.find_by(name: "Keith Moon"))
Gig.fourth.book_musician(Musician.find_by(name: "Al Kooper"))
